<!--#IFDEF _Datei1 -->
<TABLE_nav>
<TR>
   <TD ALIGN=CENTER>
   <A HREF="Datei3.HTML">Zum Ende</A>
   <A HREF="Datei2.HTML">Weiter</A>
   </TD>
</TR>
</TABLE>
<!--#ENDIF-->

<!--#IFDEF _Datei2 -->
<TABLE_nav>
<TR>
   <TD ALIGN=CENTER>
   <A HREF="Datei1.HTML">Zur&uuml;ck</A>&nbsp;
   <A HREF="Datei3.HTML">Weiter</A>
</TD>
</TR>
</TABLE>
<!--#ENDIF-->

<!--#IFDEF _Datei3 -->
<TABLE_nav>
<TR>
   <TD ALIGN=CENTER>
   <A HREF="Datei2.HTML">Zur&uuml;ck</A>&nbsp;
   <A HREF="Datei1.HTML">Zum Anfang</A>&nbsp;
</TD>
</TR>
</TABLE>
<!--#ENDIF-->
