<!--#IFDEF _Datei1 -->
<TABLE_nav>
<TR>
   <TD ALIGN=CENTER>
   <FONT _FontHigh>1 </FONT>
   <A HREF="Datei2.HTML">2</A>&nbsp;
   <A HREF="Datei3.HTML">3</A>
   </TD>
</TR>
</TABLE>
<!--#ENDIF-->

<!--#IFDEF _Datei2 -->
<TABLE_nav>
<TR>
   <TD ALIGN=CENTER>
   <A HREF="Datei1.HTML">1</A>&nbsp;
   <FONT _FontHigh>2 </FONT>
   <A HREF="Datei3.HTML">3</A>
   </TD>
</TR>
</TABLE>
<!--#ENDIF-->

<!--#IFDEF _Datei3 -->
<TABLE_nav>
<TR>
   <TD ALIGN=CENTER>
   <A HREF="Datei1.HTML">1</A>&nbsp;
   <A HREF="Datei2.HTML">2</A>&nbsp;
   <FONT _FontHigh>3 </FONT>
   </TD>
</TR>
</TABLE>
<!--#ENDIF-->

