<!--## DOCTYPE_def Version 0.1 (21.03.1999), by Thorsten Willert -->
<!--#DEFINE HTML_4_Trans '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">' -->
<!--#DEFINE HTML_4_Frame '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Frameset//EN">' -->
<!--#DEFINE HTML_4 '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">' -->
<!--#DEFINE HTML_32 '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">' -->
<!--#DEFINE HTML_2 '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 2.0//EN">' -->
