<!--## font_def Version 0.3 (30.01.2000), by Thorsten Willert -->
<!--#DEFINE <FONT_RD> '<FONT COLOR=red>' -->
<!--#DEFINE <FONT_GN> '<FONT COLOR=green>' -->
<!--#DEFINE <FONT_BL> '<FONT COLOR=blue>' -->
<!--#DEFINE <FONT_YW> '<FONT COLOR=yellow>' -->
<!--#DEFINE <FONT_MN> '<FONT COLOR=maroon>' -->
<!--#DEFINE <FONT_TL> '<FONT COLOR=teal>' -->
<!--#DEFINE <FONT_C(_v1)> '<FONT COLOR=_v1>' -->
<!--#DEFINE <FONT+1> '<FONT SIZE="+1">' -->
<!--#DEFINE <FONT-1> '<FONT SIZE="-1">' -->
<!--#DEFINE <FONT_S(_v1)> '<FONT SIZE=_v1>' -->
<!--#DEFINE <FONT_SC(_v1,_v2)> '<FONT SIZE=_v1 COLOR=_v2>' -->
