<!--## MetaVar_def Version 0.3 (05.12.1999), Thorsten Willert -->
<META HTTP-EQUIV="Content-Type" CONTENT="text/html;CHARSET=iso-8859-1">
<META HTTP-EQUIV="Erstellt" CONTENT="<!--#FILEDATE dd.mm.yyyy-->">
<META NAME="Content-Language" CONTENT="de">
<META NAME="generator" CONTENT="CompressHTML/HTML_Preprozessor">
<META NAME="author" CONTENT="_Autor">
<META NAME="publisher" CONTENT="_Autor">
<META NAME="copyright" CONTENT="_Autor">
