<!--## std_def Version 0.5 (05.12.1999), Thorsten Willert -->
<!--#DEFINE <BODY_std> '<BODY BGCOLOR="#BBBBBB">' -->
<!--#DEFINE <H1_I> '<H1><I>' -->
<!--#DEFINE </H1_I> '</I></H1>' -->
<!--#DEFINE <DIV_C> '<DIV ALIGN=CENTER>' -->
<!--#DEFINE <DIV_R> '<DIV ALIGN=RIGHT>' -->
<!--#DEFINE <DIV_L> '<DIV ALING=LEFT>' -->
<!--#DEFINE <IMG(_v1,_v2,_v3)> '<IMG SRC="_v1" ALT="_v2" <!--#IMGSIZE '_v1' --> BORDER=_v3>' -->
<!--#DEFINE <Autor(_v1)> '<DIV ALIGN=RIGHT><FONT SIZE="-1"><I><!--#FILEDATE dd. month yyyy-->, _v1</I></FONT></DIV>' -->
<!--#DEFINE <std_Date> '<!--#FILEDATE dd. month yyyy -->' -->
<!--#DEFINE <MAIL(_v1)> '<A HREF="mailto:_Mail?subject=_v1">' -->
<!--#DEFINE <HOME> '<A HREF="http://_Home">' -->
