<!--## table_def Version 0.3 (16.04.1999), Thorsten Willert -->
<!--#DEFINE <TABLE(v1,v2,v3,v4,v5)> '<TABLE WIDTH=v1 BORDER=v2 CELLPADDING=v3 CELLSPACING=v4 BGCOLOR=v5>' -->
<!--#DEFINE <TRow> '<TR>\n\t<TD>' -->
<!--#DEFINE </TRow> '</TD>\n</TR>\n' -->
<!--#DEFINE MARKER '</TD>\n\t<TD>' -->
<!--#DEFINE <TABLE_std> '<TABLE BORDER=0 WIDTH="90%" CELLSPACING=3 BGCOLOR="#CCCCCC">' -->
<!--#DEFINE <TD_VT> '<TD VALIGN=TOP>' -->
<!--#DEFINE <TD_AC> '<TD ALIGN=CENTER>' -->
<!--#DEFINE <TD_AR> '<TD ALIGN=RIGHT>' -->
